name: Build and Package Desktop App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          cd server
          pip install -r requirements.txt

      - name: Install Node.js dependencies
        run: |
          npm install
          cd react
          npm install
          cd ../electron
          npm install

      - name: Build React app
        run: |
          cd react
          npm run build

      - name: Build Electron app
        run: |
          cd electron
          npm run build

      - name: Package Electron app
        run: |
          cd electron
          npm run package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: desktop-app-${{ matrix.os }}
          path: |
            electron/dist/
            electron/release/
